INSERT INTO level(name, iso, created_by, created_date, updated_by, last_update) VALUES
('LEVEL_0', 'LVL_0', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
('LEVEL_1', 'LVL_1', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW())