INSERT INTO public.role(id, name, created_by, created_date, updated_by, last_update) VALUES
    (0, 'ROLE_ADMIN', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
	(1, 'ROLE_SECRETARY', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
	(2, 'ROLE_USER', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW());