INSERT INTO role(name, created_by, created_date, updated_by, last_update) VALUES
    ('ROLE_ADMIN', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
	('ROLE_SECRETARY', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
	('ROLE_USER', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW());