INSERT INTO status(name, created_by, created_date, updated_by, last_update) VALUES
    ('USER_SUSPENDED_BY_SUPERADMIN', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('USER_SELF_SUSPENDED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('USER_ACTIVATED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('USER_DISABLED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),

    ('ENTERPRISE_NULL', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('ENTERPRISE_NOT_VERIFIED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('ENTERPRISE_BEING_VERIFIED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('ENTERPRISE_VERIFIED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),

    ('TRANSACTION_CONFIRMED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_IN_CONFIRMATION', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_INITIATED', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_INVALID', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_CRYPTO_New', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_CRYPTO_Expired', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_CRYPTO_Processing', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_CRYPTO_Settled', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
    ('TRANSACTION_CRYPTO_Invalid', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW());


-- ALTER SEQUENCE currency_id_seq RESTART WITH 16;