INSERT INTO transaction_option(id, name, created_by, created_date, updated_by, last_update) VALUES
(1, 'OM', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
(2, 'MOMO', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW()),
(3, 'CRYPTO_TRANSFER', 'APPLICATION_DEFAULT_USER', NOW(), 'APPLICATION_DEFAULT_USER', NOW());